services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.server
    depends_on:
      - ollama
      - db
      - redis
    ports:
      - "5000:5000"
    networks:
      - api
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: 1
              capabilities: ["gpu"]

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - api

  ollama:
    volumes:
      - ./ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0:11434
    networks:
      - portaai
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: 1
              capabilities: ["gpu"]

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - api
  
  db:
    container_name: db
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: api_user
      POSTGRES_PASSWORD: api_password
      POSTGRES_DB: api_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - api

networks:
  api:
    external: false

volumes:
  db_data: